#!/bin/bash
m_warp() {
    local y='\033[1;33m'
    local BGX="\033[42m"
    local CYAN="\033[96m"
    local Putih='\033[97m'
    local RED='\033[0;31m'
    local NC='\033[0m'
    local green='\033[0;32m'
    local BIBlack='\033[1;90m'
    local BIGreen='\033[1;92m'
    local BIYellow='\033[1;93m'
    local BIBlue='\033[1;94m'
    local BIPurple='\033[1;95m'
    local BICyan='\033[1;96m'
    local BIWhite='\033[1;97m'
    local UWhite='\033[4;37m'
    local On_IPurple='\033[0;105m'
    local On_IRed='\033[0;101m'
    local IBlack='\033[0;90m'
    local IGreen='\033[0;92m'
    local IYellow='\033[0;93m'
    local IBlue='\033[0;94m'
    local IPurple='\033[0;95m'
    local ICyan='\033[0;96m'
    local IWhite='\033[0;97m'
    local GREENBO='\033[1;32m'
    local bgwhite='\e[40;97;1m'
    local bgred='\e[41;97;1m'
    local bggreen='\e[42;97;1m'
    local bgyellow='\e[43;97;1m'
    local bgmagenta='\e[45;97;1m'
    local bgblue='\e[46;97;1m'
    local bgblack='\e[47;30;1m'
    local w='\033[97m'
    local ORANGE='\033[0;34m'
    local Lime='\e[38;5;155m'

    clear
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    echo -e "${Lime}WARP MANAGER${NC}"
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    echo -e "${BIBlue}[${BIWhite}01${BIBlue}] ${NC}${BIWhite}Install Warp Client${NC}"
    echo -e "${BIBlue}[${BIWhite}02${BIBlue}] ${NC}${BIWhite}Uninstall Warp Client${NC}"
    echo -e "${BIBlue}[${BIWhite}03${BIBlue}] ${NC}${BIWhite}Restart Warp Client${NC}"
    echo -e "${BIBlue}[${BIWhite}04${BIBlue}] ${NC}${BIWhite}Activate Warp Proxy Mode${NC}"
    echo -e "${BIBlue}[${BIWhite}05${BIBlue}] ${NC}${BIWhite}Deactivate Warp Proxy Mode${NC}"
    echo -e "${BIBlue}[${BIWhite}06${BIBlue}] ${NC}${BIWhite}Warp Wireguard${NC}"
    echo -e "${BIBlue}[${BIWhite}07${BIBlue}] ${NC}${BIWhite}Warp IPv4${NC}"
    echo -e "${BIBlue}[${BIWhite}08${BIBlue}] ${NC}${BIWhite}Warp IPv6${NC}"
    echo -e "${BIBlue}[${BIWhite}09${BIBlue}] ${NC}${BIWhite}Warp Ipv4 & IPv6${NC}"
    echo -e "${BIBlue}[${BIWhite}10${BIBlue}] ${NC}${BIWhite}Warp Routing${NC}"
    echo -e "${BIBlue}[${BIWhite}11${BIBlue}] ${NC}${BIWhite}Restart Warp Wireguard${NC}"
    echo -e "${BIBlue}[${BIWhite}12${BIBlue}] ${NC}${BIWhite}Stop Warp Wireguard${NC}"
    echo -e "${BIBlue}[${BIWhite}13${BIBlue}] ${NC}${BIWhite}Warp Status${NC}"
    echo -e "${BIBlue}[${BIWhite}14${BIBlue}] ${NC}${BIWhite}Warp Version${NC}"
    echo -e "${BIBlue}[${BIWhite}15${BIBlue}] ${NC}${BIWhite}Warp Help${NC}"
    echo -e "${BIBlue}[${BIWhite}16${BIBlue}] ${NC}${BIWhite}Warp Chinese Menu${NC}"
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    echo -e "${Lime}Input 0 or x » To-${BIWhite}Exit${NC}"
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    echo ""
    read -p "Select menu :" opt
    echo -e ""
    case $opt in
    1) clear ; bash <(curl -fsSL git.io/warp.sh) install ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    2) clear ; bash <(curl -fsSL git.io/warp.sh) uninstall ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    3) clear ; bash <(curl -fsSL git.io/warp.sh) restart ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    4) clear ; bash <(curl -fsSL git.io/warp.sh) proxy ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    5) clear ; bash <(curl -fsSL git.io/warp.sh) unproxy ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    6) clear ; bash <(curl -fsSL git.io/warp.sh) wg ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    7) clear ; bash <(curl -fsSL git.io/warp.sh) wg4 ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    8) clear ; bash <(curl -fsSL git.io/warp.sh) wg6 ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    9) clear ; bash <(curl -fsSL git.io/warp.sh) wgd ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    10) clear ; bash <(curl -fsSL git.io/warp.sh) wgx ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    11) clear ; bash <(curl -fsSL git.io/warp.sh) rwg ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    12) clear ; bash <(curl -fsSL git.io/warp.sh) dwg ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    13) clear ; bash <(curl -fsSL git.io/warp.sh) status ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    14) clear ; bash <(curl -fsSL git.io/warp.sh) version ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    15) clear ; bash <(curl -fsSL git.io/warp.sh) help ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    16) clear ; bash <(curl -fsSL git.io/warp.sh) menu ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m_warp ;;
    0|x) clear ; menu ;;
    *) echo "anda salah tekan" ; sleep 1 ; m_warp ;;
    esac
}

m_warp